"""file saving in database

Revision ID: 216127cc7adb
Revises: 8112c2d4d1cb
Create Date: 2026-02-19 10:06:49.348742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216127cc7adb'
down_revision: Union[str, Sequence[str], None] = '8112c2d4d1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_documents', sa.Column('file_path', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_ocr_documents_file_path'), 'ocr_documents', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_documents_file_path'), table_name='ocr_documents')
    op.drop_column('ocr_documents', 'file_path')
    # ### end Alembic commands ###
