"""add_enterprise_tables

Revision ID: 50c3a20f9a82
Revises: a1b2c3d4e5f6
Create Date: 2026-02-24 11:40:47.855046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c3a20f9a82'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('advance_bill', sa.Float(), nullable=False),
    sa.Column('due_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'partial_paid', 'due', name='enterprisepaymentstatus'), nullable=False),
    sa.Column('no_of_documents', sa.Integer(), nullable=False),
    sa.Column('pages_used', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_created_by'), 'enterprises', ['created_by'], unique=False)
    op.create_index(op.f('ix_enterprises_email'), 'enterprises', ['email'], unique=False)
    op.create_index(op.f('ix_enterprises_id'), 'enterprises', ['id'], unique=False)
    op.create_index(op.f('ix_enterprises_is_deleted'), 'enterprises', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_enterprises_name'), 'enterprises', ['name'], unique=False)
    op.create_index(op.f('ix_enterprises_payment_status'), 'enterprises', ['payment_status'], unique=False)
    op.create_table('enterprise_ocr_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('ocr_mode', sa.String(length=50), nullable=False),
    sa.Column('ocr_engine', sa.String(length=255), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('pages_data', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_ocr_documents_enterprise_id'), 'enterprise_ocr_documents', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_enterprise_ocr_documents_filename'), 'enterprise_ocr_documents', ['filename'], unique=False)
    op.create_index(op.f('ix_enterprise_ocr_documents_id'), 'enterprise_ocr_documents', ['id'], unique=False)
    op.create_index(op.f('ix_enterprise_ocr_documents_processed_by'), 'enterprise_ocr_documents', ['processed_by'], unique=False)
    op.alter_column('ocr_documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocr_documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_enterprise_ocr_documents_processed_by'), table_name='enterprise_ocr_documents')
    op.drop_index(op.f('ix_enterprise_ocr_documents_id'), table_name='enterprise_ocr_documents')
    op.drop_index(op.f('ix_enterprise_ocr_documents_filename'), table_name='enterprise_ocr_documents')
    op.drop_index(op.f('ix_enterprise_ocr_documents_enterprise_id'), table_name='enterprise_ocr_documents')
    op.drop_table('enterprise_ocr_documents')
    op.drop_index(op.f('ix_enterprises_payment_status'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_name'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_is_deleted'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_id'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_email'), table_name='enterprises')
    op.drop_index(op.f('ix_enterprises_created_by'), table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
